/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-12-26 09:29:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class generate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/common/checkIsLogin.jsp", Long.valueOf(1419414035000L));
    _jspx_dependants.put("/common/generateContent.jsp", Long.valueOf(1419555983782L));
    _jspx_dependants.put("/common/content_left.jsp", Long.valueOf(1419490154457L));
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1419414035000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String path = request.getContextPath(); String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/"; 
      out.write(" \r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");

if(session.getAttribute("projectName")==null ){
	response.sendRedirect("login.jsp");
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>模型生成</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\" type=\"text/css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/content_left.css\" type=\"text/css\"></link>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/jquery-1.11.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#bg{ display: none;  position: absolute;  top: 0%;  left: 0%;  width: 100%;  height: 100%;  background-color: black;  z-index:1001;  -moz-opacity: 0.5;  opacity:0.5;  filter: alpha(opacity=50);}\r\n");
      out.write("    #show{display: none;  position: absolute;  top: 25%;  left: 22%;  width: 53%;  height: 49%;  padding: 8px;  border: 8px solid #E8E9F7;  background-color: white;  z-index:1002;  overflow: auto; text-align:center; line-height: 49%; font-size: 18px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//初始化左侧比对列表\r\n");
      out.write("\tfunction getHistoryList(projectName, pageNo) {\r\n");
      out.write("\t\tvar pageNo = $(\"#pageNo\").val();\r\n");
      out.write("\t\tif (pageNo == \"\") {\r\n");
      out.write("\t\t\tpageNo=1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\turl: \"compareHistory/getList.do?projectName=\"+projectName+\"&pageNo=\"+pageNo,\r\n");
      out.write("\t\t\tsuccess: fillLeftHistoryList,\r\n");
      out.write("\t\t\terror: function(error) {\r\n");
      out.write("\t\t\t\talert(\"比对历史加载失败!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//在页面载入的时候，加载比对记录列表\r\n");
      out.write("\t\tgetHistoryList($(\"#projectName\").val(), $(\"#pageNo\").val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#upFile\").change(function(){\r\n");
      out.write("\t\t\tvar filename = $(this).val();\r\n");
      out.write("\t\t\talert(\"change():\" + filename);\r\n");
      out.write("\t\t\t$(\"#originalUploadFileName\").val(filename);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#upload\").submit(function(){\r\n");
      out.write("\t\t\t$.ajaxFileUpload({\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/upload.do',\r\n");
      out.write("\t\t\t\tsecureuri:false,\r\n");
      out.write("\t\t\t\tfileElementId:'upFile',\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: function(result, status) {\r\n");
      out.write("\t\t\t\t\talert(result+ \"--\" + result.success + \"--\" + status);\r\n");
      out.write("\t\t\t\t\tif (result.success == \"1\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"上传文件成功！\");\r\n");
      out.write("\t\t\t\t\t\tvar filename=getFileNameFromFilePath(result.fileRelativePath);\r\n");
      out.write("\t\t\t\t\t\t$(\"#upload_info\").html(\"<div>文件:\"+ filename +\"   <a href='javascript:void(0)' onclick='deletefile(\"+\"\\\"\"+result.fileRelativePath+\"\\\",\\\"designFile\\\")'>删除</a>\"+\"<br/></div>\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#upload_info\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#designRelativeFilePath\").val(result.fileRelativePath);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#upload_info\").html(\"文件上传失败: \" + result.msg);\r\n");
      out.write("\t\t\t\t\t\t$(\"#upload_info\").css({\"visibility\":\"visible\", \"color\":\"red\"});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcomplete: function(xmlHttpRequest, status) {\r\n");
      out.write("\t\t\t\t\t$(\"#upFile\").replaceWith(\"<input type=\\\"file\\\" id=\\\"upFile\\\" name=\\\"upFile\\\" style=\\\"display:none;\\\"/>\");\r\n");
      out.write("\t\t\t\t\t$(\"#upFile\").change(function(){\r\n");
      out.write("\t\t\t\t\t\tvar filename = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t$(\"#originalUploadFileName\").val(filename);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data, status, e) {\r\n");
      out.write("\t\t            alert(\"文件上传失败!\" + data.msg+\" error:  \" + e); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#generate\").click(function(){\r\n");
      out.write("\t\t\tvar designRelativeFilePath = $(\"#designRelativeFilePath\").val();\r\n");
      out.write("\t\t\tif(designRelativeFilePath == \"\") {\r\n");
      out.write("\t\t\t\talert(\"请上传数据库设计文件!\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl: \"generate.do?designRelativeFilePath=\"+designRelativeFilePath,\r\n");
      out.write("\t\t\t\tbeforeSend: function(xmlHttpRequest) {\r\n");
      out.write("\t\t\t\t\tshowMask();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(data, status) {\r\n");
      out.write("\t\t\t\t\tif(data.success == \"0\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"数据模型生成失败： \" + data.msg);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t   var form = $(\"<form>\");   //定义一个form表单\r\n");
      out.write("\t\t\t\t       form.attr('style','display:none');   //在form表单中添加查询参数\r\n");
      out.write("\t\t\t\t       form.attr('target','');\r\n");
      out.write("\t\t\t\t       form.attr('method','post');\r\n");
      out.write("\t\t\t\t       form.attr('action',\"downloadFile.do\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t       var input1 = $('<input>'); \r\n");
      out.write("\t\t\t\t       input1.attr('type','hidden'); \r\n");
      out.write("\t\t\t\t       input1.attr('name','filePath'); \r\n");
      out.write("\t\t\t\t       input1.attr('value',data.filePath); \r\n");
      out.write("\t\t\t\t       $('body').append(form);  //将表单放置在web中\r\n");
      out.write("\t\t\t\t       form.append(input1);   //将查询参数控件提交到表单上\r\n");
      out.write("\t\t\t\t       form.submit();   //表单提交\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcomplete:function(xmlHttpRequest, status) {\r\n");
      out.write("\t\t\t\t\tcloseMask();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"bg\"></div>\r\n");
      out.write("\t<div id=\"show\">\r\n");
      out.write("\t\t<p>createTable脚本正在生成，请耐心等待。。。</p>\r\n");
      out.write("\t\t<img src=\"images/waiting.gif\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"Container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div id=\"Header\">\r\n");
      out.write("\t<div class=\"logo\">\r\n");
      out.write("\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/logo.png\">\r\n");
      out.write("\t\t<img width=\"139\" height=\"34\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/title.png\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"logoutPanel\" align=\"right\">\r\n");
      out.write("\t\t项目组： ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <a href=\"login.jsp\">登出</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<div id=\"Content\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"Content_Left\">\r\n");
      out.write("\t<div id=\"menus\">\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a class=\"task-icon-link\" href=\"main.jsp\">\r\n");
      out.write("\t\t\t\t<img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" src=\"images/VersionManager.png\">\r\n");
      out.write("\t\t\t</a>&nbsp;\r\n");
      out.write("\t\t\t<a class=\"task-link\" href=\"main.jsp\">版本管理</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a class=\"task-icon-link\" href=\"export.jsp\">\r\n");
      out.write("\t\t\t\t<img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" src=\"images/download.png\">\r\n");
      out.write("\t\t\t</a>&nbsp;\r\n");
      out.write("\t\t\t<a class=\"task-link\" href=\"export.jsp\">模型导出</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a class=\"task-icon-link\" href=\"generate.jsp\">\r\n");
      out.write("\t\t\t\t<img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" src=\"images/download.png\">\r\n");
      out.write("\t\t\t</a>&nbsp;\r\n");
      out.write("\t\t\t<a class=\"task-link\" href=\"generate.jsp\">模型生成</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a class=\"task-icon-link\" href=\"compare.jsp\">\r\n");
      out.write("\t\t\t\t<img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" src=\"images/new.png\">\r\n");
      out.write("\t\t\t</a>&nbsp;\r\n");
      out.write("\t\t\t<a class=\"task-link\" href=\"compare.jsp\">新建比对</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"compareHistory\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"pane-header\">\r\n");
      out.write("\t\t\t\tCompare History\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"pane-content\">\r\n");
      out.write("\t\t\t<table id=\"historyList\">\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<input name=\"projectName\" type=\"hidden\" id=\"projectName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<input name=\"pageNo\" type=\"hidden\" id=\"pageNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"Main_Panel\">\r\n");
      out.write("\t<div id=\"Main_Panel_Content\">\r\n");
      out.write("\t\t<label>上传数据库设计文件（Excel格式 .xls）:</label>\r\n");
      out.write("\t\t<div id=\"uploadDiv\">\r\n");
      out.write("\t\t\t<form id=\"upload\"> \r\n");
      out.write("\t     \t   <span>基准数据：</span>\r\n");
      out.write("\t     \t   <input type=\"text\" onclick=\"$('#upFile').click()\" id=\"originalUploadFileName\" size=\"40\" /> \r\n");
      out.write("\t           <input type=\"button\" onclick=\"$('#upFile').click()\" value=\"浏览\"/>\r\n");
      out.write("\t           <input type=\"file\" id=\"upFile\" name=\"upFile\" style=\"display:none;\"/> &nbsp;\r\n");
      out.write("\t           <input type=\"submit\" value=\"上传\"> \r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"upload_info\" style=\"width:100%;height:20px;visibility:hidden\" ></div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input id=\"designRelativeFilePath\" name=\"designRelativeFilePath\" type=\"hidden\">\r\n");
      out.write("\t\t\t<input id=\"generate\" type=\"button\" value=\"生成\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div> ");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
